//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bild
    {
        public Bild()
        {
            this.Bild_Reise = new HashSet<Bild_Reise>();
            this.Bild_Unterkunft = new HashSet<Bild_Unterkunft>();
        }
    
        public int id { get; set; }
        public byte[] bild1 { get; set; }
        public Nullable<System.DateTime> erstelldatum { get; set; }
    
        public virtual ICollection<Bild_Reise> Bild_Reise { get; set; }
        public virtual ICollection<Bild_Unterkunft> Bild_Unterkunft { get; set; }
    }
}
