//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        public Buchung()
        {
            this.Bewertung = new HashSet<Bewertung>();
        }
    
        public int reisedetail_id { get; set; }
        public Nullable<System.DateTime> erstelldatum { get; set; }
    
        public virtual ICollection<Bewertung> Bewertung { get; set; }
        public virtual Kunde Kunde { get; set; }
        public virtual Reisedetail Reisedetail { get; set; }
    }
}
