//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reisebueroEntities : DbContext
    {
        public reisebueroEntities()
            : base("name=reisebueroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresse> Adresse { get; set; }
        public DbSet<Benutzer> Benutzer { get; set; }
        public DbSet<Bewertung> Bewertung { get; set; }
        public DbSet<Bild> Bild { get; set; }
        public DbSet<Bild_Reise> Bild_Reise { get; set; }
        public DbSet<Bild_Unterkunft> Bild_Unterkunft { get; set; }
        public DbSet<Buchung> Buchung { get; set; }
        public DbSet<Kunde> Kunde { get; set; }
        public DbSet<Land> Land { get; set; }
        public DbSet<Mitarbeiter> Mitarbeiter { get; set; }
        public DbSet<Reise> Reise { get; set; }
        public DbSet<Reisedetail> Reisedetail { get; set; }
        public DbSet<Unterkunft> Unterkunft { get; set; }
        public DbSet<Verpflegung> Verpflegung { get; set; }
    }
}
