//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reise
    {
        public Reise()
        {
            this.Bild_Reise = new HashSet<Bild_Reise>();
            this.Reisedetail = new HashSet<Reisedetail>();
        }
    
        public int id { get; set; }
        public string titel { get; set; }
        public string beschreibung { get; set; }
        public decimal preis_erwachsener { get; set; }
        public decimal preis_kind { get; set; }
        public Nullable<System.DateTime> erstelldatum { get; set; }
    
        public virtual ICollection<Bild_Reise> Bild_Reise { get; set; }
        public virtual Unterkunft Unterkunft { get; set; }
        public virtual ICollection<Reisedetail> Reisedetail { get; set; }
    }
}
