//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unterkunft
    {
        public Unterkunft()
        {
            this.Bild_Unterkunft = new HashSet<Bild_Unterkunft>();
            this.Reise = new HashSet<Reise>();
        }
    
        public int id { get; set; }
        public string bezeichnung { get; set; }
        public string beschreibung { get; set; }
        public int kategorie { get; set; }
        public Nullable<System.DateTime> erstelldatum { get; set; }
    
        public virtual ICollection<Bild_Unterkunft> Bild_Unterkunft { get; set; }
        public virtual ICollection<Reise> Reise { get; set; }
        public virtual Verpflegung Verpflegung { get; set; }
    }
}
