//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Versandhaus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class versandhausEntities : DbContext
    {
        public versandhausEntities()
            : base("name=versandhausEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artikel> AlleArtikel { get; set; }
        public DbSet<ArtikelDetail> AlleArtikelDetails { get; set; }
        public DbSet<ArtikelGeloescht> AlleArtikelGeloescht { get; set; }
    }
}
